### ISSUE TITLE
exists pragma for SPF and macros

### ISSUE THREAD

**Issue by tspinksindeed** [leonamp/SPFBL#100]
There does not appear to be support for SPF records that use the exists pragma or macro expansions. 

This results in false positive results failing SPF checks despite having valid SPF record

**Comment by leonamp** [comment]
You can see the code for mechanism exists here:

https://github.com/leonamp/SPFBL/blob/ce3619a703243ad841a84c8b151d3dd066df0775/src/net/spfbl/spf/SPF.java#L1662

and the code for macro expansion here:

https://github.com/leonamp/SPFBL/blob/ce3619a703243ad841a84c8b151d3dd066df0775/src/net/spfbl/spf/SPF.java#L686

If you have any other questions, just let me know.
