### ISSUE TITLE
Adicionando block permanente 

### ISSUE THREAD

**Issue by ncaio** [leonamp/SPFBL#26]
Estou enfrentando problemas em adicionar um remetente na blacklist =]

```
[01fea44c130 client]# bash -x spfbl.sh block add parceiro@smtp.sitedomelhordesconto.com.br
+ IP_SERVIDOR=localhost
+ PORTA_SERVIDOR=9877
+ PORTA_ADMIN=9875
+ DUMP_PATH=/tmp
+ QUERY_TIMEOUT=10
+ export PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/sbin:/usr/local/bin
+ PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/sbin:/usr/local/bin
+ version=1.04
+ case $1 in
+ case $2 in
+ '[' 3 -lt 3 ']'
+ sender=parceiro@smtp.sitedomelhordesconto.com.br
++ nc localhost 9877
++ echo 'BLOCK ADD parceiro@smtp.sitedomelhordesconto.com.br'
+ response='ERROR: CLIENT INVALID'
+ [[ ERROR: CLIENT INVALID == '' ]]
+ echo 'ERROR: CLIENT INVALID'
ERROR: CLIENT INVALID
+ [[ ERROR: CLIENT INVALID == \T\I\M\E\O\U\T ]]
+ [[ ERROR: CLIENT INVALID == \O\K ]]
+ exit 1
```

```
bash-4.2# telnet 10.2.1.6 9877
Trying 10.2.1.6...
Connected to 10.2.1.6.
Escape character is '^]'.
BLOCK ADD www-data@
ERROR: CLIENT INVALID
Connection closed by foreign host.

```

**Comment by leonamp** [comment]
Opa Noilson,

Esqueci de documentar nesta nova versão que a identificação de cliente
passou a ser obrigatória.

Na versão antiga, quando o cliente não era identificado, o SPFBL indexava
os registros destas listas num cliente dummy.

Para resolver o problema você vai precisar fazer alguns procedimentos:
1. Criar um cliente mesmo que este seja o próprio terminal:
   - spfbl.sh client add <cidr> <domain> (SPFBL|DNSBL|ALL|NONE) [<email>]
   - spfbl.sh client add 127.0.0.1/32 domain.tld ALL admin@domain.tld
2. Fazer um dump na base:
   - spfbl.sh dump > spfbl.dump
3. Abrir o arquivo do dump e trocar os registros do cliente dummy pelo
   e-mail do cliente cadastrado em 1 e
4. Carregar o arquivo dump novamente.

Lembrando que é prudente copiar os arquivos da base na pasta /data antes de
realizar todo este procedimento.

Os registros do cliente dummy são aqueles iniciando por um IP seguido de
dois pontos. Exemplo:

127.0.0.1:@domain.tld

(trocar para o email do novo cliente)

admin@domain.tld:@domain.tld

Convido você a entrar na nossa lista de discussão para receber nossos
alertas sobre o projeto:

https://groups.google.com/d/forum/spfbl

Se eu puder ajudar em qualquer outro assunto, pode contar comigo.

Abraços,
Leandro

2016-04-27 17:09 GMT-03:00 Noilson Caio T. de Araújo <
notifications@github.com>:

**Comment by ncaio** [comment]
Obrigado
