### ISSUE TITLE
Bloqueio de servidor com PTR Ok ao devolver um MAIL DELIVERY

### ISSUE THREAD

**Issue by diegocanton** [leonamp/SPFBL#71]
Olá, tenho alguns servidores MTA, onde nossos clientes de link de internet podem utilizar para hospedagem de seus sites/emails. Recentemente um cliente entrou em contato por não conseguir enviar mensagens, ao verificar vi que o IP está sendo bloqueado pela SPFBL.

Segundo a sua documentação, bastaria identificar o erro 5.7.1 no MTA e agir sob esse erro, acontece que a mensagem retornada é "550 5.7.1 SPFBL you are permanently blocked on this server."

Agora entra o problema, durante a analise, meu servidor negou uma mensagem da origem que me bloqueou, enviando para eles um "2016-12-12 09:48:51 [22609] 1cGP69-0005sf-Jr <= <> R=1cGP68-0005iv-O6 U=mailnull P=local S=39254 M8S=0 T="Mail delivery failed: returning message to sender" from <> for USUARIO@traXXX.me", este MTA em questão parece ter me bloqueado por devolver um MAIL DELIVERY.

Gostaria de saber como posso proceder para que este servidor volte a enviar mensagens.
Caso seja necessário, posso entrar em contato direto para fornecer logs completos.

**Comment by leonamp** [comment]
Diego,

Quando o MTA recebe esse prefixo "5.7.1 SPFBL" na rejeição SPFBL, tem que
tratar o problema para não receber os pontos negativos no IP do mesmo MTA.

Este caso que você mostrou é um bloqueio do remetente feito pelo
destinatário.

Para tratar este problema, existem duas soluções possíveis: conversar com o
administrador do MTA de destino para rever a política de bloqueio no
destinatário ou parar de enviar mensagens deste remetente para o
destinatário especifico, no caso de se tratar de spammer.

Leandro Carlos Rodrigues

Em 14 de dezembro de 2016 19:39, Diego Canton de Brito <
notifications@github.com> escreveu:

**Comment by diegocanton** [comment]
Leandro, no caso, este servidor não esta tentando enviar mais esta mensagem, mas outros dominios no servidor estão tentando enviar mensagens para outros destinos, dentro desta politica, haveria o caso destas tentativas estarem incrementando?

Lembrando que o LOG aponta uma mensagem que foi recebida por uma caixa cheia e retornada ao remetente, com isso houve o bloqueio.

Verifiquei e após essa mensagem só há retorno de DNSBL, já não sendo mais respostas do SPFBL diretamente. 

Outro ponto estranho está no fato de haver o PTR deste servidor e o SPFBL dizer que o FCrDNS é inválido. Já testei isso com NSLOOKUP, no postmaster do TERRA e em outras 3 ferramentas, todas indicam que há PTR apontando para o dominio do servidor e o dominio para o IP.

**Comment by leonamp** [comment]
De qual IP exatamente estamos falando?

Leandro Carlos Rodrigues

Em 14 de dezembro de 2016 19:55, Diego Canton de Brito <
notifications@github.com> escreveu:

**Comment by diegocanton** [comment]
Já testei outros IPs que utilizou e apenas este apresenta essa situação 187.17.160.15

**Comment by leonamp** [comment]
Este IP está com FCrDNS válido:

http://matrix.spfbl.net/dnsbl/187.17.160.15

O único problema com ele é a reputação ruim. O FCrDNS está de acordo.

É preciso tratar o problema e esperar vencer esses pontos negativos para
poder fazer o delisting beleza?

Leandro Carlos Rodrigues

2016-12-14 20:03 GMT-02:00 Diego Canton de Brito <notifications@github.com>:

**Comment by diegocanton** [comment]
Desculpa leandro, realmente, estive realizando testes e acabei não observando que a consulta que eu fiz foi no servidor que me bloqueou.

http://spfbl.molservidores.com/dnsbl/187.17.160.15

Bom, o MAIL DELIVERY já foi removido por ter expirado. Mas vejo emails de outros clientes sendo recusados via DNSBL, minha preocupação é que o IP não seja liberado por causa dessas consultas.

Vi sua apresentação na GTER e gostei muito do projeto, gostaria de parabeniza-lo pelo trabalho. Estou com um parecer favorável da equipe para subir um host e integra-lo aos nossos cPanels.

**Comment by leonamp** [comment]
Opa. Valeu!

Mas uma coisa que você deve observar é que SPFBL e DNSBL são dois serviços
distintos.

A gente usa o SPFBL nos nossos MTAs mas publicamos o DNSBL com o único
propósito de forçar os enviadores a respeitarem esse prefixo de rejeição
SPFBL que bolamos. A ideia é conter o fluxo indesejado na origem.

Quando você diz que está sendo barrado pelo pessoal que usa nossa DNSBL,
essas rejeições não implicam em pontuação negativa.

A pontuação negativa parte exclusivamente dos prefixos de rejeição SPFBL.

Você já apurou o problema apontado nesses prefixos? Já tomou providências?

Veja antes o que está acontecendo para eu poder te ajudar beleza?

Leandro Carlos Rodrigues

Em 14 de dezembro de 2016 20:17, Diego Canton de Brito <
notifications@github.com> escreveu:

**Comment by diegocanton** [comment]
Sim, já avaliei os logs e me certifiquei, o contato foi exatamente por ter essa dúvida. Estou tentando conseguir o contato do pessoal que realizou o bloqueio, cheguei a um dominio Brasileiro e estou entrando em contato. Nos logs só há o retorno de um dominio/servidor depois todos os outros são dados de DNSBL mesmo.

Você acaba de me tirar a dúvida que tinha, resolvendo com o reportador o problema deve ser sanado, acredito que ele esteja com uma versão com algum BUG, veja que o server dele indica que meu IP está inválido, tudo deve ter começado dai.

Obrigado pela atenção.

**Comment by leonamp** [comment]
Hum. Agora entendi o problema. Seu IP está com FCrDNS supostamente
inválido, mas isso por si só não faz com que uma consulta SPFBL retorne que
o IP é inválido na rejeição SMTP.

Para que isso ocorra, é preciso que o FCrDNS seja inválido e ao mesmo tempo
o remetente enviado não autorize explicitamente tal IP para envio lá no SPF
dele.

Ainda que ocorra falha de software na validação FCrDNS, esse problema pode
ser resolvido com a inclusão do IP no registro SPF do domínio do remetente.
Se o SPF do remetente der PASS, o SPFBL vai ignorar o fato do IP estar com
FCrDNS inválido, ainda que seja uma falha de software na validação.

Leandro Carlos Rodrigues

Em 14 de dezembro de 2016 20:28, Diego Canton de Brito <
notifications@github.com> escreveu:

**Comment by ghost** [comment]
Diego,

o que retorna em http://dnsbl.spfbl.net/*meuip ?*

**Comment by diegocanton** [comment]
Esse link me parece estar errado.


Em http://dnsbl.spfbl.net/dnsbl/187.17.160.15 e http://matrix.spfbl.net/dnsbl/187.17.160.15
```
Resultado da checagem DNSBL do IP 187.17.160.15.

Reversos encontrados:
<ns1.ensite.com.br> FCrDNS válido.
Este IP está listado por má reputação com 75% de pontos negativos do volume total de envio.

Para que este IP possa ser removido desta lista,
é necessário que o MTA de origem reduza o volume de envios para os destinatários
cuja rejeição SMTP tenha prefixo '5.7.1 SPFBL <message>'.

Cada rejeição SMTP com este prefixo gera automaticamente um novo ponto negativo neste sistema, onde este ponto expira em uma semana.

O motivo da rejeição pode ser compreendida pela mensagem que acompanha o prefixo.
```


No Servidor que me bloqueou http://spfbl.molservidores.com/dnsbl/187.17.160.15

```
Resultado da checagem DNSBL do IP 187.17.160.15.

Reversos encontrados:
<ns1.ensite.com.br> FCrDNS inválido.
Este IP foi bloqueado por má reputação com 88% de pontos negativos do volume total de envio.

Para que este IP possa ser removido desta lista,
é necessário que o MTA de origem reduza o volume de envios para os destinatários
cuja rejeição SMTP tenha prefixo '5.7.1 SPFBL <message>'.

Cada rejeição SMTP com este prefixo gera automaticamente um novo ponto negativo neste sistema, onde este ponto expira em uma semana.

O motivo da rejeição pode ser compreendida pela mensagem que acompanha o prefixo.

Powered by SPFBL.net
```

**Comment by diegocanton** [comment]
Estou aguardando resposta do pessoal do molservidores.com, acredito que um bug na versão que ele usa combinado com algum filtro resultou no bloqueio do IP.

Veja que as respostas são diferentes de cada URL.

PS: Essa URL dele foi um "chute" que dei ao analisar como funciona o SPFBL, o padrão se confirmou no servidor dele e então usei para consultar e ver se teria algum detalhe a mais.

Em todo caso pode fechar a thread. Pelo que o Leandro passou, como não há mais a mensagem na fila de entrega, a reputação deve se resolver sozinha nos próximos dias.

**Comment by leonamp** [comment]
Diego,

Eu dei uma investigada no código fonte e contatei que não há defeito na
validação do FCrDNS.

O que ocorreu ai, certamente tem a ver com o servidor DNS do provedor de
destino, onde a informação não se propagou corretamente.

O simples fato de haver um problema no DNS do provedor de destino, que
causou a não validação do FCrDNS, não faz com que haja esse resultado
"invalid" que você presenciou no prefixo de rejeição SPFBL. Para que haja
esse resultado, além do FCrDNS estar inválido, é necessário também que o
SPF não esteja válido.

Por este motivo, peço que avalie o SPF de todos os domínios que usam este
MTA para saída. O IP deste MTA tem que estar em todos os SPFs deles.

Fazendo isso, na possibilidade do mesmo problema de DNS ocorrer novamente,
tanto com este como outros provedores, o retorno "invalid" não irá ocorrer
e com isso pontuar negativamente seu IP.

Para te ajudar nesse problema, eu acabei de resetar os pontos negativos
deste seu IP aqui no nosso servidor SPFBL.

Entretanto eu peço que conserte os registros SPF destes domínios na saída
para minimizar a probabilidade de ocorrer o mesmo problema.

Qualquer problema que tiver, entre em contato pelo leandro@spfbl.net pois
vou fechar a thread aqui beleza?

Leandro Carlos Rodrigues

Em 14 de dezembro de 2016 23:07, Diego Canton de Brito <
notifications@github.com> escreveu:
