### ISSUE TITLE
Instalação

### ISSUE THREAD

**Issue by ghost** [leonamp/SPFBL#86]
Olá!

Tem como instalar on premises e utilizar como gateway smtp multi-tenant?

Obrigado.

**Comment by ncaio** [comment]
On promises, sim. Você pode ter o seu próprio servidor SPFBL. Seja ele isolado ou dentro de um peer, privado ou oficial.
O SPFBL não é um servidor SMTP, mas pode ser utilizado por um servidor MTA no modo GATEWAY que atende várias instâncias (multi-tenant).  Você pode criar políticas de checagem para cada instância dos seus tenants apontando para uma única instância SPFBL ou até ter uma instância SPFBL para cada tenant. =]

**Comment by ghost** [comment]
OK muito obrigado!
