### ISSUE TITLE
Integration Exim SPFBL

### ISSUE THREAD

**Issue by mucke5** [leonamp/SPFBL#96]
Hello. The link to "geturldomainlist"[./run/exim.pl](https://github.com/leonamp/SPFBL/blob/master/run/exim.pl) is invalid.

Are these [instructions](https://github.com/leonamp/SPFBL/wiki/Integra%C3%A7%C3%A3o-com-Exim-SPFBL) for integrating Exim DNSBL also applicable for the current version Exim 4.92 ?

---
As a side note, is [Exim URIBL](https://www.dropbox.com/s/5aorrijafw5ygk0/uribl.pl?dl=0) also possible to be integrated ?

**Comment by leonamp** [comment]
Hi. The documentation is not updated. You can use the file https://github.com/leonamp/SPFBL/blob/master/client/uribl.pl, name it as exim.pl and continue to follow the instructions. I will fix this documentation right now. Thanks!

**Comment by leonamp** [comment]
I forgot to say that the new function is getListHREF!

**Comment by mucke5** [comment]
Thank you for your fast improvement! Could you advise me which uribl.pl is better, the one at [GitHub](https://github.com/leonamp/SPFBL/blob/master/client/uribl.pl) or the beta at [Dropbox ](https://www.dropbox.com/s/5aorrijafw5ygk0/uribl.pl?dl=0) ?
---
Would the DNSBL based on SPFBL be integrated like this ?
`dnslists = zen.spamhaus.org : dnsbl.spfbl.net`
`CHECK_RCPT_DOMAIN_DNSBLS = dnsbl.spfbl.net/$sender_address_domain`

**Comment by mucke5** [comment]
Should [hasblackext](https://github.com/leonamp/SPFBL/blob/master/run/hasblackext) instead of hasblackext2 be entered in following line:
`condition = ${run{/usr/local/bin/hasblackext2 "$mime_decoded_filename"}{false}{true}}`

**Comment by mucke5** [comment]
Both conditions have the same value 15. Can you have a look, please ?
`  # Accept messages from same network.
  warn
    log_message = SPFBL same network.
    condition = ${if eq {$acl_c_spfreceived}{15}{true}{false}}
  accept
    condition = ${if eq {$acl_c_spfreceived}{15}{true}{false}}`

**Comment by leonamp** [comment]
> 
> ## Thank you for your fast improvement! Could you advise me which uribl.pl is better, the one at [GitHub](https://github.com/leonamp/SPFBL/blob/master/client/uribl.pl) or the beta at [Dropbox ](https://www.dropbox.com/s/5aorrijafw5ygk0/uribl.pl?dl=0) ?
> 
> Would the DNSBL based on SPFBL be integrated like this ?
> `dnslists = zen.spamhaus.org : dnsbl.spfbl.net`
> `CHECK_RCPT_DOMAIN_DNSBLS = dnsbl.spfbl.net/$sender_address_domain`

They are the same today. There is no more a beta.

**Comment by leonamp** [comment]
> 
> 
> Should [hasblackext](https://github.com/leonamp/SPFBL/blob/master/run/hasblackext) instead of hasblackext2 be entered in following line:
> `condition = ${run{/usr/local/bin/hasblackext2 "$mime_decoded_filename"}{false}{true}}`

That is it. I forgot to update the documentation, but I just did it.

**Comment by leonamp** [comment]
> 
> 
> Both conditions have the same value 15. Can you have a look, please ?
> ` # Accept messages from same network. warn log_message = SPFBL same network. condition = ${if eq {$acl_c_spfreceived}{15}{true}{false}} accept condition = ${if eq {$acl_c_spfreceived}{15}{true}{false}}`

Ok. The first condition is just for log purposes. You can omit it if you want.

**Comment by mucke5** [comment]
> Would the DNSBL based on SPFBL be integrated like this ?
`dnslists = zen.spamhaus.org : dnsbl.spfbl.net`
`CHECK_RCPT_DOMAIN_DNSBLS = dnsbl.spfbl.net/$sender_address_domain`

Could you answer this, please?

**Comment by mucke5** [comment]
I read a [comment](http://spamassassin.1065346.n5.nabble.com/low-score-on-very-spammy-email-tp151155p151167.html) of you mentioning "Documentation to set this DNSBL at SA". There is only rspamd configuration available. Where are you listing such SpamAssassin configuration?

**Comment by leonamp** [comment]
> 
> 
> > Would the DNSBL based on SPFBL be integrated like this ?
> > `dnslists = zen.spamhaus.org : dnsbl.spfbl.net`
> > `CHECK_RCPT_DOMAIN_DNSBLS = dnsbl.spfbl.net/$sender_address_domain`
> 
> Could you answer this, please?

Yes. You can setup our DNSBL like spamhaus.org and you can query sender domain too.

Take a look at this Rspamd setup and see if this setup is useful for you:

    https://spfbl.net/en/rspamd

**Comment by leonamp** [comment]
> 
> 
> I read a [comment](http://spamassassin.1065346.n5.nabble.com/low-score-on-very-spammy-email-tp151155p151167.html) of you mentioning "Documentation to set this DNSBL at SA". There is only rspamd configuration available. Where are you listing such SpamAssassin configuration?

You can setup your SA like other DNSBLs. Use our DNSWL to negative scores and our URIBL like uribl.com examples.

**Comment by mucke5** [comment]
The definition of the SPFBL variable `set acl_c_reject = false` has no influence. Can you please explain that?

**Comment by leonamp** [comment]
> 
> 
> The definition of the SPFBL variable `set acl_c_reject = false` has no influence. Can you please explain that?

You are right. Just ignore it ok?
