### ISSUE TITLE
English README version

### ISSUE THREAD

**Issue by ZEROF** [leonamp/SPFBL#97]
Hello,

Can your translate README to English? I try to understand why only your RBL is blocking my emails. Same on your site, https://spfbl.net/en/project/, as you're using /en in url even google don't want to translate that page.

Best regards

**Comment by leonamp** [comment]
Hi. We don't support RBL issues here. This channel is only for SPFBL source code issues. Sorry!

**Comment by ZEROF** [comment]
This is not about RBL issue, this is about documentation and trying to learn about your system and configuration. And without English documentation it's little hard to understand everything.

Thanks

**Comment by leonamp** [comment]
Ok. This project started in Brazil, for Brazilian providers needs, so we will keep the documentation in Portuguese until the project become international some day.
