### ISSUE TITLE
Forbidden

### ISSUE THREAD

**Issue by brudarko** [leonamp/SPFBL#98]
Olá pessoal, tudo bem?

Estou instalando a ferramenta juntamente com o Zimbra.
Segui os passos da instação, mas ao digitar a chave OTP, a página seguinte fica assim:
![image](https://user-images.githubusercontent.com/25669568/102942041-06ce5980-4493-11eb-9fd3-49522deb645c.png)

Alguma ideia do que pode ser?

Grato!

**Comment by leonamp** [comment]
Olá. Como vai? Não se preocupe pois essa tela será preenchida assim que aparecerem os primeiros registros. Este é um defeito meramente estético. Saudações!

**Comment by brudarko** [comment]
Oi Leonardo!

Então, eu instalei ontem de meio-dia mas ainda sim aparece como forbbiden.
Nota que estou usando CentOS 8. Preciso fazer alguma outra configuração?

Nos logs tenho isso:
HTTP GET /1608727099845 => 403 text/plain Forbidden\n
HTTP GET /favicon.ico => 403 text/plain Forbidden\n

Também tenho um grande número de e-mails, então acredito que já devia ter carregado :(

**Comment by leonamp** [comment]
É certo que não houve registros de consulta para este usuário especifico, já que a parte inferior da tela mostra nenhuma linha, exceto aquela que é mostrada apenas para clicar e o sistema mostrar mais registros. Uma vez que houver registros de consulta para este usuário, você poderá clicar em qualquer uma destas linhas para que essa tela superior seja devidamente preenchida com a informação referente a linha selecionada. Se nenhuma linha for selecionada, essa versão de sistema atual mostra "Forbiden", mas mostrar "Forbiden", quando nenhuma linha é selecionada, é um problema meramente estético e não interfere na operação normal do sistema. Esse defeito estético será corrigido nas próximas versões.
